### ISSUE TITLE
Champion 4 and scroll window 

### ISSUE THREAD

**Issue by Bastigom** [DeadwoodJedi/speed-calculator-bug-tracker#53] opened 2021-04-07 09:26 UTC
**Champion 4 is not easy to insert information with iPhone.. it doesent scroll down fully so you cant see. And just as much the window doesent sense the scroll . Instead the underneath part is scrolling Instead. See prints 
![311E5327-6DD6-4DEB-8022-D38635C17B43](https://user-images.githubusercontent.com/82088767/113843491-e7361500-9793-11eb-9573-55d3f8a7f753.jpeg)
![FA5D7E93-943E-47D1-86E7-86A0870C451C](https://user-images.githubusercontent.com/82088767/113843497-e9986f00-9793-11eb-8ae0-e3b75303d41f.png)

**

**To Reproduce**

**Expected behavior**
Be able to insert information and see the table you want to insert it in.

**Screenshots** added

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):** iPhone newest 

**Additional context**

**Comment by mitchelkuijpers** [comment] 2021-04-12 07:33
Duplicate of: #47 I will continue to add updates there.

**Closed by mitchelkuijpers** 2021-04-12 07:33 UTC
Labels: duplicate
