### ISSUE TITLE
Turn number incorrect when CB is faster than team

### ISSUE THREAD

**Issue by aldaris** [DeadwoodJedi/speed-calculator-bug-tracker#4] opened 2021-01-19 14:19 UTC
**Describe the bug**
When checking UNM 1:1 composition where all the team has < 190 speed, the turn numbers displayed become incorrect, and turn 1 is listed twice.

**To Reproduce**
1. Set up a CB team where all champions have <190 speed
2. The cell in the first row first column will show Turn number 1, but so will the cell in the first row second column

**Expected behavior**
In this case I guess the numbering should be 1-2-3, and for teams that are faster than CB: 0-1-2 as it is right now.

**Comment by mitchelkuijpers** [comment] 2021-01-19 20:49
I managed to reproduce this, thank you for the bug. Will look into this in the next few days.

**Comment by mitchelkuijpers** [comment] 2021-01-19 21:54
The bug is fixed and deployed it now looks like this:

![image](https://user-images.githubusercontent.com/621140/105097617-329c2980-5aa9-11eb-8f9d-3d3657cf3c67.png)

I'll close this issue now.

**Closed by mitchelkuijpers** 2021-01-19 21:54 UTC
Labels: bug
